neverware: remove incorrect comma from printk call
Fixes this warning:

    /mnt/host/source/src/third_party/kernel/neverware-v4.14/drivers/mfd/kempld-core.c: In function 'kempld_init':
    /mnt/host/source/src/third_party/kernel/neverware-v4.14/drivers/mfd/kempld-core.c:838:4: warning: too many arguments for format [-Wformat-extra-args]
        printk(KERN_WARNING, "kempld_core: Neverware: disabling kempld_core due to hardware match.\n");